name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Baixar artefato do Build
        uses: actions/download-artifact@v4
        with:
          name: sistema-bancario-jar
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar JAR como artefato do Deploy
        uses: actions/upload-artifact@v4
        with:
          name: sistema-bancario-deploy
          path: sistema-bancario-*.jar
